= Chapter 4: File I/O: The Universal I/O Model
Aakash Gupta <uchanahome8@gmail.com>
:toc:

== 4.1 Overview
* File descriptor.
* 0 for `stdin`, 1 for `stdout` and 2 for `stderr`.
* Four key system calls:
** `fd = open(pathname, flags, mode)`.
** `numread = read(fd, buffer, count)`.
** `numwritten = write(fd, buffer, count)`.
** `status = close(fd)`.

== 4.2. Universality of I/O
One of the distinguishing features of the UNIX I/O model is the concept of
universality of I/O. This means that the same four system calls—open(), read(), write(),
and close()—are used to perform I/O on all types of files, including devices such as
terminals. Consequently, if we write a program using only these system calls, that
program will work on any type of file.

== 4.3 Opening a File: `open()`

****
[source,c]
----
#include <sys/stat.h>
#include <fcntl.h>

int open(const char *pathname, int flags, ... /* mode_t mode */);
----
****

****
[source,c]
----
#include <fcntl.h>

int creat(const char *pathname, mode_t mode);
----
****
The `creat()` system call creates and opens a new file with the given pathname, or if the file already exists, opens the file and truncates it to zero length.

NOTE: Calling creat() is equivalent to the following open() call: `fd = open(pathname, O_WRONLY | O_CREAT | O_TRUNC, mode);`.

== 4.4 Reading from a File: `read()`
****
[source,c]
----
#include <unistd.h>

ssize_t read(int fd, void *buffer, size_t count);
----
****

* The `count` argument specifies the maximum number of bytes to read.
* The `buffer` argument supplies the address of the memory buffer into which the input data is to be placed.
* This buffer must be at least `count` bytes long.
* A call to `read()` may read less than the requested number of bytes. For a regular file, the probable reason for this is that we were close to the end of the file.
* If a terminating null byte is required at the end of the input buffer, we must put it there explicitly:
****
[source,c]
----
char buffer[MAX_READ + 1];
ssize_t numRead;

numRead = read(STDIN_FILENO, buffer, MAX_READ);
if (numRead == -1)
    errExit("read");

buffer[numRead] = '\0';
printf("The input data was: %s\n", buffer);
----
****
* To read exactly `n` bytes, refer this:

****
[source,c]
----
ssize_t readn(int fd, void *vptr, size_t n)
{
    size_t nleft;
    ssize_t nread;
    char *ptr;

    ptr = vptr;
    nleft = n;

    while (nleft > 0) {
        if ((nread = read(fd, ptr, nleft)) < 0) {
            if (errno == EINTR)
                nread = 0; /* and call read() again */
            else
                return (-1);
        } else if (nread == 0)
            break; /* EOF */
        nleft -= nread;
        ptr += nread;
    }

    return (n - nleft); /* return >= 0 */
}
----
****

== 4.5 Writing to a File: `write()`
****
[source,c]
----
#include <unistd.h>

ssize_t write(int fd, void *buffer, size_t count);
----
****

* `buffer` is the address of the data to be written.
* `count` is the number of bytes to write from buffer.
* `fd` is a file descriptor referring to the file to which data is to be written.

* To write exactly `n` bytes, refer this:
****
[source,c]
----
ssize_t writen(int fd, const void *vptr, size_t n)
{
    size_t nleft;
    ssize_t nwritten;
    const char *ptr;

    ptr = vptr;
    nleft = n;

    while (nleft > 0) {
        if ( (nwritten = write(fd, ptr, nleft)) <= 0) {
            if (nwritten < 0 && errno == EINTR)
                nwritten = 0; /* and call write() again */
            else
                return (-1); /* error */
        }
        nleft -= nwritten;
        ptr += nwritten;
    }

    return (n);
}
----
****
== 4.6 Closing a File: `close()`
* When a process terminates, all of its open file descriptors are automatically closed.
****
[source,c]
----
#include <unistd.h>

int close(int fd);
----
****

== 4.7 Changing the File Offset: `lseek()`
* This is the location in the file at which the next `read()` or `write()` will commence.
****
[source,c]
----
#include <unistd.h>

off_t lseek(int fd, off_t offset, int whence);
----
****

* `whence` can be `SEEK_SET`/`SEEK_CUR`/`SEEK_END`.

=== File holes

* It is possible to write bytes at an arbitrary point past the end of the file.
** The space in between the previous end of the file and the newly written bytes is
referred to as a *file hole*.
** From a programming point of view, the bytes in a hole
exist, and reading from the hole returns a buffer of bytes containing 0 (null bytes).
** File holes don’t, however, take up any disk space. The file system doesn’t allocate any disk blocks for a hole until, at some later point, data is written into it

User can use the following command to see the actual file system size of a file with file holes:
****
[source,bash]
----
du -h <filename>
----
****

== 4.8 Operations Outside the Universal I/O Model: `ioctl()`
****
[source,c]
----
#include <sys/ioctl.h>

int ioctl(int fd, int request, ... /* argp */);
----
****
== Questions
****
[source,c]
----
include::../chap4/4.1.cpp[]
----
****

****
[source,c]
----
include::../chap4/4.2.cpp[]
----
****